# Generated by Django 5.2.8 on 2025-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_alter_receipt_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="currency",
            field=models.CharField(blank=True, default="USD", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="store_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="line_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="receiptitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
